#!/usr/bin/env sh
rm -rf /usr/repos/*
git clone https://github.com/kiss-community/repo-main /usr/repos/official
git clone https://github.com/kiss-community/repo-community /usr/repos/community

kiss update
kiss build $1
